In [1]:
import numpy as np

In [3]:
one_dimensional_array=np.array([1.2,2.4,3.5,4.7,6.1,7.2,8.3,9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [7]:
two_dimensional_array=np.array([[6,5],[11,7],[4,8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [9]:
sequence_of_integers=np.arange(5,12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [12]:
random_integers_between_50_and_100=np.random.randint(low=50,high=101,size=(6))
print(random_integers_between_50_and_100)

[100  74  99  63  66  93]


In [14]:
random_floats_between_0_and_1=np.random.random([6])
print(random_floats_between_0_and_1)

[0.36206839 0.44967721 0.70300797 0.87719873 0.88043261 0.52358948]


In [16]:
random_floats_between_2_and_3=random_floats_between_0_and_1+2.0
print(random_floats_between_2_and_3)

[2.36206839 2.44967721 2.70300797 2.87719873 2.88043261 2.52358948]


In [19]:
feature=np.arange(6,21)
label=(3*feature)+4
print(feature)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]
